#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
go_root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$go_root/.." && pwd)"
scratch_dir="$(mktemp -d "${TMPDIR:-/tmp}/pretty-cli-docs.XXXXXX")"
trap 'rm -rf "$scratch_dir"' EXIT

pretty_bin="$scratch_dir/pretty"
output_tmp="$scratch_dir/CLI.md"
output="$repo_root/docs/CLI.md"

(cd "$go_root" && go build -buildvcs=false -o "$pretty_bin" ./cmd/pretty)
top_help="$($pretty_bin help)"

commands=()
while IFS= read -r command; do
  commands[${#commands[@]}]="$command"
done < <(
  printf '%s\n' "$top_help" | awk '
    /^Daily workflows:$/ { in_commands = 1; next }
    /^Global flags/ { in_commands = 0 }
    in_commands && /^  [[:alnum:]][[:alnum:]-]*/ { print $1 }
  '
)

if ((${#commands[@]} == 0)); then
  printf 'gen-cli-docs: no commands found in top-level help\n' >&2
  exit 1
fi

{
  printf '%s\n\n' '<!-- GENERATED by scripts/gen-cli-docs.sh — do not edit -->'
  printf '# Pretty CLI reference\n\n'
  printf 'This reference is generated from the built `pretty` command registry in `prettygo/cmd/pretty/help.go`.\n\n'
  printf '## Top-level help\n\n```text\n%s\n```\n' "$top_help"

  for command in "${commands[@]}"; do
    printf '\n## `pretty %s`\n\n```text\n' "$command"
    "$pretty_bin" help "$command"
    printf '```\n'
  done
} >"$output_tmp"

mv "$output_tmp" "$output"
